### ISSUE TITLE
"No module named lex" error

### ISSUE THREAD

**Issue by tom77** [asl2/PyZ3950#4]
Hi There,

This is a great project, thanks for putting it together.
I'm having an error when trying to run the hello.py script from my (windows) python 2.7.x instance:

```
C:\Python27\python.exe hello.py
Traceback (most recent call last):
  File "hello.py", line 2, in <module>
    from PyZ3950 import zoom
  File "C:\Python27\lib\site-packages\PyZ3950\zoom.py", line 73, in <module>
    from PyZ3950 import ccl
  File "C:\Python27\lib\site-packages\PyZ3950\ccl.py", line 124, in <module>
    import lex
ImportError: No module named lex
```
any suggestions?

**Comment by Kijewski** [comment]
You need to `pip install ply`. The requirement is not installed automatically with PyZ3950.

**Comment by tom77** [comment]
Thanks @Kijewski 

Still no luck unfortunately. It successfully imported ply to my C:\Python27\Lib\site-packages but I'm still getting the following. I'll try on my Linux machine later today.

C:\Python27\python.exe hello.py
Traceback (most recent call last):
  File "hello.py", line 2, in <module>
    from PyZ3950 import zoom
  File "C:\Python27\lib\site-packages\PyZ3950\zoom.py", line 73, in <module>
    from PyZ3950 import ccl
  File "C:\Python27\lib\site-packages\PyZ3950\ccl.py", line 124, in <module>
    import lex
ImportError: No module named lex

**Comment by MarsitFaysel** [comment]
for linux :+1: 
python2.7.x :sudo apt-get install python-ply
python 3.x: sudo apt-get install python3-ply
https://www.howtoinstall.co/en/ubuntu/utopic/python-ply

**Comment by tsulimancsi** [comment]
how do you do this on Mac ?  and I have also ran `pip install ply `

**Comment by cclauss** [comment]
Need to modify `import lex` to [`from ply import lex`](https://github.com/asl2/PyZ3950/blob/master/PyZ3950/ccl.py#L124).
